spring:
  application:
    name: subway-monitor
  #  data:
  #    mongodb:
  #      host: 127.0.0.1
  #      port: 27017
  #      database: subway
  datasource:
    name: subwayData
    url: jdbc:mysql://127.0.0.1:3306/subwayData
    username: root
    password: yangguang52199
    #    password: Yangguang52199!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml
  #    username:
  #    password:
  #    uri: mongodb://mall_log:FDxUEGprQ0R9@10.16.208.238:27018/mall_log
  kafka:
    # 指定kafka 代理地址，可以多个
    producer:
      bootstrap-servers: 47.92.211.92:9092
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      # 缓存容量
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 47.92.211.92:9092
      # 指定默认消费者group id
      group-id: consumer-tutorial
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # 指定listener 容器中的线程数，用于提高并发量
    listener:
      concurrency: 3
server:
  port: 8003
  profiles:
    active: dev